<?php
// module/Product/view/product/product/edit.phtml:

$title = 'Edit Item';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url(
    'product',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('itemname'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('boughtat'));
echo $this->formRow($form->get('overheads'));
echo $this->formRow($form->get('soldat'));
echo $this->formRow($form->get('sold'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();