<?php
// module/Album/view/album/album/index.phtml:

$title = 'All Products';
//$this->headTitle($title);
$url_order = 'ASC'; // the following lines
if ($order_by == 'itemname')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'description')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>


<h1><?php echo $title; ?></h1>
<p>
    <a href="<?php echo $this->url('product', array('action' => 'add')); ?>">Add new item</a>
    <a href="<?php echo $this->url('product', array('action' => 'index')); ?>">Return to home page</a>
</p>

<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('list', array('order_by' => 'itemname', 'order' => $url_order)); ?>">Itemname <?php if ($order_by == 'itemname'): ?>
                <i class="fa fa-chevron-up<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('list', array('order_by' => 'description', 'order' => $url_order)); ?>">Description <?php if ($order_by == 'description'): ?>
                <i class="fa fa-chevron-up<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('list', array('order_by' => 'date', 'order' => $url_order)); ?>">Date <?php if ($order_by == 'date'): ?>
                <i class="fa fa-chevron-up<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>Bought At</th>
        <th>Overheads</th>
        <th>Sold At</th>
        <th>Sold</th>
        <th>Profit</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $product) : ?>
        <?php

        $sold = $this->escapeHtml($product->sold);

        if ($sold == 1) {

            $soldTag = '<span class="label label-success">Sold</span>';

        } else {

            $soldTag = '<span class="label label-default">Not Sold</span>';

        }




        ?>
        <tr>
            <td><?php echo $this->escapeHtml($product->itemname); ?></td>
            <td><?php echo $this->escapeHtml($product->description); ?></td>
            <td><?php echo $this->escapeHtml($product->date); ?></td>
            <td><?php echo number_format($this->escapeHtml($product->boughtat), 2, '.', '');; ?></td>
            <td><?php echo number_format($this->escapeHtml($product->overheads), 2, '.', '');; ?></td>
            <td><?php echo number_format($this->escapeHtml($product->soldat), 2, '.', '');; ?></td>
            <td><?php echo $soldTag ?></td>
            <td><?php echo number_format($this->escapeHtml($product->profit), 2, '.', '');; ?></td>
            <td>
                <a href="<?php echo $this->url('product',
                    array('action' => 'edit', 'id' => $product->id));?>"><i class="fa fa-edit"></i></a>
                <a href="<?php echo $this->url('product',
                    array('action' => 'delete', 'id' => $product->id));?>"><i class="fa fa-trash-o"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php

echo $this->paginationControl(
    $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order)
);
?>

