<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %seBay Profit Calculator%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Use this free ebay calculator to search for items and calculate your profit!'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="/product"><?php echo $this->translate('Start your empire! Click to search for an item') ?> &raquo;</a></p>
</div>
